version: '3.7'
services:
  agh:
    image: adguard/adguardhome
    restart: always
    ports:
      - 53:53
      - 82:80/tcp
      - 3000:3000
      - 853:853/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf

volumes:
  adguard_work:
  adguard_conf:
    