version: '3'
services:
  service1:
    image: <image_name>
    ports:
      - <host_port>:<container_port>
    volumes:
      - <host_path>:<container_path>
    environment:
      - <key>=<value>
    # Add more services here if needed

