version: '3'

volumes:
  key_db_vol:

services:
  keycloak:
    image: bitnami/keycloak:latest
    restart: always
    ports:
      - 8191:8080
    links:
      - keydb
    depends_on:
      - keydb
    environment:
      - KEYCLOAK_ADMIN=$KEY_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KEY_PASS
      - KEYCLOAK_DATABASE_HOST=dbkeydb
      - KEYCLOAK_DATABASE_PORT=3808
      - KEYCLOAK_DATABASE_USER=$DB_USER
      - KEYCLOAK_DATABASE_PASSWORD=$DB_PASS
      - KEYCLOAK_DATABASE_NAME=$DB_NAME

  keydb:
    image: postgres:11
    ports: 5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - key_db_vol:/var/lib/postgresql/data




