version: '3'
services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - AIP_ENDPOINT=
      - CLIENT_ENDPOINT=
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - spot_mongo:/data/db
  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - 3000:3000
    environment:
      - API_ENDPOINT=

volumes:
  spot_mongo: